const exchanges = [
  {
    name: 'Bitfinex',
    ticker: 'BITF',
    base: 'USD',
    assetTicker: 'BTC',
    show: true,
    inverted: false,
    enabled: true,
    includeInAverage: true,
  },
  {
    name: 'Bitflyer',
    ticker: 'FLYR',
    base: 'JPY',
    assetTicker: 'BTC',
    show: true,
    inverted: false,
    enabled: true,
    includeInAverage: true,
  },
  {
    name: 'Bitmex',
    ticker: 'BMEX',
    base: 'USD',
    assetTicker: 'XBT',
    show: true,
    inverted: false,
    enabled: true,
    includeInAverage: false,
  },
  {
    name: 'Binnace',
    ticker: 'BINA',
    base: 'USDT',
    assetTicker: 'BTC',
    show: false,
    inverted: false,
    enabled: true,
    includeInAverage: true,
  },
  {
    name: 'Bitstamp',
    ticker: 'BITS',
    base: 'USD',
    assetTicker: 'BTC',
    show: false,
    inverted: true,
    enabled: true,
    includeInAverage: true,
  },
  {
    name: 'Coinbase',
    ticker: 'GDAX',
    base: 'USD',
    assetTicker: 'BTC',
    show: true,
    inverted: false,
    enabled: true,
    includeInAverage: true,
  },
  {
    name: 'Gemini',
    ticker: 'GMNI',
    base: 'USD',
    assetTicker: 'BTC',
    show: false,
    inverted: false,
    enabled: true,
    includeInAverage: true,
  },
  {
    name: 'Kraken',
    ticker: 'KRKN',
    base: 'USD',
    assetTicker: 'XBT',
    show: false,
    inverted: false,
    enabled: true,
    includeInAverage: true,
  },
  {
    name: 'OKEX',
    ticker: 'OKEX',
    base: 'USDT',
    assetTicker: 'BTC',
    show: false,
    inverted: false,
    enabled: true,
    includeInAverage: true,
  },
];

export default exchanges;
